---
- hosts: all
  sudo: yes
  roles:
    - basic

- hosts: ldap
  sudo: yes
  roles:
    - ldap

- hosts: ldap1
  sudo: yes
  roles:
    - ldap_primary

- hosts: sftp
  sudo: yes
  roles:
    - sftp

- hosts: web
  sudo: yes
  roles:
    - web
    - nfs